export const ESPECIALIDADES = [
  'Acompañamiento Terapéutico',
  'Administración de Salud',
  'Cardiología',
  'Cirugía General',
  'Clínica Médica',
  'Dermatología',
  'Endocrinología',
  'Estimulación Temprana',
  'Fisiatría',
  'Fonoaudiología',
  'Gastroenterología',
  'Gerontología',
  'Ginecología y Obstetricia',
  'Hematología',
  'Infectología',
  'Kinesiología',
  'Medicina de Familia',
  'Medicina Estética',
  'Musicoterapia',
  'Nefrología',
  'Neurocirugía',
  'Neurología',
  'Neuropsicología',
  'Nutrición',
  'Obstetricia',
  'Odontología',
  'Oftalmología',
  'Oncología',
  'Ortopedia',
  'Otorrinolaringología',
  'Pediatría',
  'Psicología',
  'Psicopedagogía',
  'Psiquiatría',
  'Psiquiatría Infanto-Juvenil',
  'Reumatología',
  'Secretariado Médico',
  'Terapia Ocupacional',
  'Traumatología',
  'Urología',
  'Otro / No listado',
]
